
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/ST/STM32CubeCLT_1.17.0/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:31 (project)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Windows - 10.0.22631 - 
...
